// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ProviderSession from "@/components/SessionProvider";
import Navbar from "@/components/Navbar";
import NavbarAvatar from "@/components/Navbars";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Script untuk set dark mode sebelum render */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const darkMode = localStorage.getItem('darkMode') === 'true';
                document.documentElement.classList.toggle('dark', darkMode);
                if (darkMode) {
                  document.body.style.backgroundColor = '#1a1a1a'; // Warna latar belakang gelap
                  document.body.style.color = '#ffffff'; // Warna teks gelap
                } else {
                  document.body.style.backgroundColor = '#ffffff'; // Warna latar belakang terang
                  document.body.style.color = '#000000'; // Warna teks terang
                }
              })();
            `,
          }}
        />
      </head>
      <body>
        <ProviderSession>
          <NavbarAvatar />
          <div className="w-full h-screen bg-background dark:bg-black text-foreground dark:text-white">
            {children}
          </div>
        </ProviderSession>
      </body>
    </html>
  );
}
